# The name of the workflow
name: First Workflow

# Controls when the workflow will run. workflow_dispatch allows manually run from the Actions tab
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The name of the job
  first-job:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Print greeting
        run: echo "Hello, world!"
        
      - name: Print goodbye
        run: echo "Done - bye!"
